//#Remove 
mods.thermalexpansion.Factorizer.removeRecipeCombine(<avaritia:resource:6> * 9);
mods.thermalexpansion.Factorizer.removeRecipeSplit(<avaritia:block_resource:1>);
recipes.removeShapeless(<avaritia:resource:6> * 9, [ <avaritia:block_resource:1>]);
recipes.remove(<projectex:final_star>);
recipes.remove(<projectex:final_star_shard>);
mods.avaritia.Compressor.remove(<avaritia:singularity:1>);
mods.avaritia.Compressor.remove(<avaritia:singularity:2>);
mods.avaritia.Compressor.remove(<avaritia:singularity:3>);
mods.avaritia.Compressor.remove(<avaritia:singularity:4>);
mods.avaritia.Compressor.remove(<avaritia:singularity:10>);
mods.avaritia.Compressor.remove(<avaritia:singularity>);
mods.avaritia.Compressor.remove(<avaritia:singularity:11>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_bow>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pickaxe>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_shovel>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_axe>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_hoe>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_helmet>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_chestplate>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_pants>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_boots>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:endest_pearl>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);
recipes.remove(<avaritia:block_resource:2>);
recipes.remove(<avaritia:block_resource:1>);
recipes.remove(<avaritia:block_resource>);
recipes.remove(<avaritia:extreme_crafting_table>);
recipes.remove(<avaritia:double_compressed_crafting_table>);
recipes.remove(<avaritia:compressed_crafting_table>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:infinity_sword>);
recipes.remove(<avaritia:resource:7>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);
recipes.remove(<avaritia:resource:5>);
recipes.remove(<avaritia:resource:4>);
recipes.remove(<avaritia:resource:3>);
recipes.remove(<avaritia:resource:2>);
recipes.remove(<avaritia:resource:1>);
recipes.remove(<avaritia:resource>);
recipes.remove(<projecte:item.pe_gem_armor_0>);
recipes.remove(<projecte:item.pe_gem_armor_1>);
recipes.remove(<projecte:item.pe_gem_armor_2>);
recipes.remove(<projecte:item.pe_gem_armor_3>);
recipes.remove(<projecte:item.pe_klein_star>);
recipes.remove(<projecte:item.pe_transmutation_tablet>);
recipes.remove(<projecte:transmutation_table>);
recipes.remove(<projecte:item.pe_philosophers_stone>);
recipes.remove(<extendedcrafting:material:13>);
recipes.remove(<extendedcrafting:material:19>);
recipes.remove(<projecte:item.pe_dm_armor_3>);
recipes.remove(<projecte:item.pe_dm_armor_2>);
recipes.remove(<projecte:item.pe_dm_armor_1>);
recipes.remove(<projecte:item.pe_dm_armor_0>);
recipes.remove(<projecte:item.pe_dm_armor_0>);
//#Add
recipes.addShaped(<contenttweaker:juusto_puuro>, [[<extrautils2:compressedcobblestone:7>, <actuallyadditions:item_food>, <contenttweaker:hartwall_kenka>],[<actuallyadditions:item_food:14>, <actuallyadditions:item_resonant_rice>, <minecraft:dragon_egg>], [<minecraft:golden_apple:1>, <minecraft:bowl>, <minecraft:rotten_flesh>]]);
recipes.addShapeless(<extrautils2:decorativesolid:6>, [<minecraft:dye:4>,<ore:blockQuartz>]);
recipes.addShaped(<contenttweaker:dark_hartwall>, [[null, <projecte:item.pe_matter>, null],[<projecte:item.pe_matter>, <contenttweaker:hartwall_original>, <projecte:item.pe_matter>], [null, <projecte:item.pe_matter>, null]]);
recipes.addShaped(<projecte:item.pe_gem_armor_0>, [[<projecte:matter_block:1>, <projecte:item.pe_klein_star:5>, <projecte:matter_block:1>], [<projecte:rm_furnace>, <projecte:item.pe_rm_armor_0>, <projecte:rm_furnace>], [<projecte:item.pe_arcana_ring>, <redstonearsenal:armor.boots_flux>, <projecte:item.pe_arcana_ring>]]);
recipes.addShaped(<projecte:item.pe_gem_armor_1>, [[<projecte:matter_block:1>, <projecte:item.pe_klein_star:5>, <projecte:matter_block:1>], [<projecte:rm_furnace>, <projecte:item.pe_rm_armor_1>, <projecte:rm_furnace>], [<projecte:matter_block:1>, <redstonearsenal:armor.legs_flux>, <projecte:matter_block:1>]]);
recipes.addShaped(<projecte:item.pe_gem_armor_2>, [[<projecte:matter_block:1>, <projecte:item.pe_klein_star:5>, <projecte:matter_block:1>], [<projecte:rm_furnace>, <projecte:item.pe_rm_armor_2>, <projecte:rm_furnace>], [<projecte:matter_block:1>, <simplyjetpacks:itemjetpack:24>, <projecte:matter_block:1>]]);
recipes.addShaped(<projecte:item.pe_gem_armor_3>, [[<projecte:matter_block:1>, <projecte:item.pe_klein_star:5>, <projecte:matter_block:1>], [<projecte:rm_furnace>, <projecte:item.pe_rm_armor_3>, <projecte:rm_furnace>], [<projecte:matter_block:1>, <redstonearsenal:armor.helmet_flux>, <projecte:matter_block:1>]]);
recipes.addShaped(<projecte:item.pe_klein_star>, [[<projecte:item.pe_fuel:2>, <projecte:item.pe_fuel:2>, <projecte:item.pe_fuel:2>], [<projecte:item.pe_fuel:2>, <ore:netherStar>, <projecte:item.pe_fuel:2>], [<projecte:item.pe_fuel:2>, <projecte:item.pe_fuel:2>, <projecte:item.pe_fuel:2>]]);
recipes.addShapeless(<ae2wtlib:wut_creative>.withTag({StoredTerminals: [{id: "wit:wit_creative", Count: 1 as byte, Damage: 0 as short}, {id: "wpt:wpt_creative", Count: 1 as byte, Damage: 0 as short}, {id: "wct:wct_creative", Count: 1 as byte, Damage: 0 as short}, {id:"wft:wft_creative", Count: 1 as byte, Damage: 0 as short}]}), [<wit:wit_creative>,<wpt:wpt_creative>,<wct:wct_creative>,<wft:wft_creative>]);
recipes.addShapeless(<extrautils2:creativechest>, [<thermalexpansion:satchel:32000>]);
recipes.addShapeless(<thermalexpansion:satchel:32000>, [<extrautils2:creativechest>]);
recipes.addShapeless(<simplyjetpacks:itemjetpack>, [<simplyjetpacks:itemjetpack:19>,<thermalexpansion:capacitor:32000>]);
recipes.addShapeless(<simplyjetpacks:itemfluxpack>, [<simplyjetpacks:itemfluxpack:10>,<thermalexpansion:capacitor:32000>]);
recipes.addShapeless(<extrautils2:creativeenergy>, [<immersiveengineering:metal_device0:3>]);
recipes.addShapeless(<immersiveengineering:metal_device0:3>, [<extrautils2:creativeenergy>]);
recipes.addShapeless(<extrautils2:itemcreativebuilderswand>, [<extrautils2:itemcreativedestructionwand>]);
recipes.addShapeless(<extrautils2:itemcreativedestructionwand>, [<extrautils2:itemcreativebuilderswand>]);
recipes.addShapeless(<extrautils2:drum:4>, [<extrautils2:drum:4>]);
recipes.addShapeless(<contenttweaker:hartwall_original> * 9, [<contenttweaker:hartwall_block>]);
recipes.addShaped(<contenttweaker:hartwall_block>, [[<contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>],[<contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>], [<contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>]]);
recipes.addShaped(<contenttweaker:hartwall_kenka> * 2, [[null, null, null],[<contenttweaker:hartwall_original>, null, <contenttweaker:hartwall_original>], [null, <minecraft:leather_boots>, null]]);
recipes.addShaped(<forge:bucketfilled>.withTag({FluidName: "harmaata", Amount: 1000}), [[<contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>],[<contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>, <contenttweaker:hartwall_original>], [<contenttweaker:hartwall_original>, <minecraft:bucket>, <contenttweaker:hartwall_original>]]);
recipes.addShaped(<contenttweaker:hartwall_original> * 8, [[<minecraft:glass_bottle>, <minecraft:glass_bottle>, <minecraft:glass_bottle>],[<minecraft:glass_bottle>, <forge:bucketfilled>.withTag({FluidName: "harmaata", Amount: 1000}), <minecraft:glass_bottle>], [<minecraft:glass_bottle>, <minecraft:glass_bottle>, <minecraft:glass_bottle>]]);
recipes.addShaped(<projecte:item.pe_dm_armor_3>, [[null, null, null],[<projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>], [<projecte:item.pe_matter>, <twilightforest:yeti_helmet>, <projecte:item.pe_matter>]]);
recipes.addShaped(<projecte:item.pe_dm_armor_2>, [[<projecte:item.pe_matter>, <twilightforest:ironwood_chestplate>, <projecte:item.pe_matter>],[<projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>], [<projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>]]);
recipes.addShaped(<projecte:item.pe_dm_armor_1>, [[<projecte:item.pe_matter>, <projecte:item.pe_matter>, <projecte:item.pe_matter>],[<projecte:item.pe_matter>, <twilightforest:fiery_leggings>, <projecte:item.pe_matter>], [<projecte:item.pe_matter>, null, <projecte:item.pe_matter>]]);
recipes.addShaped(<projecte:item.pe_dm_armor_0>, [[null, null, null],[<projecte:item.pe_matter>, null, <projecte:item.pe_matter>], [<projecte:item.pe_matter>, <twilightforest:steeleaf_boots>, <projecte:item.pe_matter>]]);
mods.immersiveengineering.Refinery.addRecipe(<liquid:harmaata> * 100, <liquid:water> * 95, <liquid:ethanol> * 5, 100);
//File End
